services:
  - type: web
    name: hip-knee-dashboard-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && gunicorn --bind 0.0.0.0:$PORT app:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
